services:
  - name: feedback-api
    type: web
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python -m nltk.downloader punkt wordnet
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9
    autoDeploy: true
